In [1]:
import pandas as pd
import numpy as np

### colors/values appearence analysis

read Excel files by quadrant

In [2]:
blackbox1_top_left_quadrant = pd.read_csv("blackbox1_top_left_quadrant.csv")
blackbox1_top_right_quadrant = pd.read_csv("blackbox1_top_right_quadrant.csv")
blackbox1_bottom_left_quadrant = pd.read_csv("blackbox1_bottom_left_quadrant.csv")
blackbox1_bottom_right_quadrant = pd.read_csv("blackbox1_bottom_right_quadrant.csv")

find missing value by step

In [24]:
l = [1,2,3,4,5,6,7,8,9,0]                #a list contain all values

In [54]:
blackbox1_top_left_quadrant.head(5)

,Unnamed: 0,"( 1, 1)","( 1, 2)","( 1, 3)","( 1, 4)","( 1, 5)","( 1, 6)","( 1, 7)","( 1, 8)","( 1, 9)",...,"( 10, 1)","( 10, 2)","( 10, 3)","( 10, 4)","( 10, 5)","( 10, 6)","( 10, 7)","( 10, 8)","( 10, 9)","( 10, 10)"
0,step: 1,3,7,0,9,6,1,3,3,4,...,8,9,6,4,0,1,0,7,4,0
1,step: 2,3,7,0,9,6,1,3,3,4,...,8,9,6,4,0,1,0,7,4,0
2,step: 3,3,7,0,9,5,1,3,3,4,...,8,9,6,4,0,1,0,7,4,0
3,step: 4,3,7,0,9,5,1,3,3,4,...,8,9,6,4,0,1,0,7,4,0
4,step: 5,3,7,0,9,5,1,3,3,4,...,8,9,6,4,0,1,0,7,4,0

In [55]:
row = []
missing_value = []
blackbox1_top_left_quadrant["missing values"] = np.nan*4000
for row_index in range(4000):
    row = blackbox1_top_left_quadrant.iloc[row_index, 1:].tolist() #extract a row
    row = np.unique(row)     #get unique values from current row
    #print(row)
    missing_value = list(set(l)-set(row))    #find missing colors/values
    blackbox1_top_left_quadrant.loc[row_index,"missing values"] = ','.join(str(missing_value))
    #print(','.join(missing_value))

In [56]:
row = []
missing_value = []
blackbox1_top_right_quadrant["missing values"] = np.nan*4000
for row_index in range(4000):
    row = blackbox1_top_right_quadrant.iloc[row_index, 1:].tolist() #extract a row
    row = np.unique(row)     #get unique values from current row
    #print(row)
    missing_value = list(set(l)-set(row))    #find missing colors/values
    blackbox1_top_right_quadrant.loc[row_index,"missing values"] = ','.join(str(missing_value))
    #print(','.join(missing_value))

In [57]:
row = []
missing_value = []
blackbox1_bottom_left_quadrant["missing values"] = np.nan*4000
for row_index in range(4000):
    row = blackbox1_bottom_left_quadrant.iloc[row_index, 1:].tolist() #extract a row
    row = np.unique(row)     #get unique values from current row
    #print(row)
    missing_value = list(set(l)-set(row))    #find missing colors/values
    blackbox1_bottom_left_quadrant.loc[row_index,"missing values"] = ','.join(str(missing_value))
    #print(','.join(missing_value))

In [58]:
row = []
missing_value = []
blackbox1_bottom_right_quadrant["missing values"] = np.nan*4000
for row_index in range(4000):
    row = blackbox1_bottom_right_quadrant.iloc[row_index, 1:].tolist() #extract a row
    row = np.unique(row)     #get unique values from current row
    #print(row)
    missing_value = list(set(l)-set(row))    #find missing colors/values
    blackbox1_bottom_right_quadrant.loc[row_index,"missing values"] = ','.join(str(missing_value))
    #print(','.join(missing_value))

In [62]:
blackbox1_top_right_quadrant.to_csv('file1.csv')